### ISSUE TITLE
Sound effect won't play?

### ISSUE THREAD

**Issue by jordanwilliams1** [thorsten-gehrig/alexa-remote-control#107]
I'm trying to play a sound effect through my echo dot but it's not working, the command I'm running is:
./alexa_remote_control.sh -e sound:'buzzers_10' 

Link of audio:
`<audio src="soundbank://soundlibrary/alarms/buzzers/buzzers_10"/>`

I've tried another effect such as: 

./alexa_remote_control.sh -e sound:'amzn_sfx_doorbell_chime_01'

and it works fine. But the effect I want doesn't? What am i doing?

**Comment by scottgrobinson** [comment]
@jordanwilliams1 I just tested with this exact command and it worked without issue. Give this a try?

`./alexa.sh -e speak:'<audio src="soundbank://soundlibrary/alarms/buzzers/buzzers_10"/>'`

**Comment by jordanwilliams1** [comment]
@scottgrobinson Thanks, That command worked for me 👍

**Comment by adn77** [comment]
@scottgrobinson , @jordanwilliams1 the reason this might work is because this get's handled as two different Alexa commands.
Sending `-e sound:...` uses *Alexa.Sound*
Sending `-e speak:...`uses *AlexaAnnouncement* (if announcments are turned on) or *Alexa.Speak*

For Alexa.Sound there's only a limited number of sounds from the soundlibrary available (you can see for youself by setting up an automation routine in the Alexa app => play sound).

For AlexaAnnouncement you can use SSML which apparently now can also access the soundlibrary (this wasn't always the case).

nice find!
