### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by skarotech** [thorsten-gehrig/alexa-remote-control#130]
Hi All, not sure if this is a new thing, but getting rate limiting errors returned after only a few announcements, extract from logs here

Rate exceeded: Too many requests.
sending cmd:speak:Warning. Drain alarm activated. to dev:Hall Echo Dot type:A1RABVCI4QCIKC serial:G0911W11042600MF customerid:A2CZ0U28C20Z51

Any ideas, or ways to fix this ?

**Comment by Korki67** [comment]
Hello Skarotech,

I am also having some difficulty with rate limiting. In my experience, it also happens when you first change loudness and after change e.g. radio station. So I wrote a script to do both with some sleep of 1/2 second inbetween loudness and next command.

This has solved my issues with all my echo's but one. The one accepts the loudness but does not run the radio. I have not yet invested time to find out what is going on here. There is no error message. The logs show the radio command without error.

Regards,
Horst

**Comment by Apollon77** [comment]
This is an limitation from amazon ... make sure you have delays in your calls

**Comment by adn77** [comment]
@skarotech I don't know your exact settings about volume control - if you have a `SPEAKVOL` other than `0` the script will query the current volume before sending the speak. There is a pause in the script before sending the actual speak comand but that might not suffice.

If you're sending the speak output to multiple devices, consider using the announcement feature as the speak command gets sent in a sequence (batch) command there.

I am also working on enabling all comands to be group-aware...

@Korki67 you should use `SPEAKVOL` and `NORMALVOL` as those commands set the volume as above mentioned sequence commands without causing rate limits.
