### ISSUE TITLE
No automation in plain text

### ISSUE THREAD

**Issue by dbochicchio** [thorsten-gehrig/alexa-remote-control#75]
As I stated, I'm searching for support to execute routines (via the automation flag) in the plain text version.

Is there any reason why it's not supported? Thanks,

**Comment by adn77** [comment]
The way the automation execution works is:
1. download all automations
2. parse the returned JSON for the utterance theuser requested (the name of the automation)
3. return that part of the JSON back to the API

the parsing of JSON in BASH is really hard - I did do it for a few things in the plain version but for the automations this is too heavy.

You can download your existing automations at https://${ALEXA}/api/behaviors/automations?limit=200 and see for yourself. Sorry, I know this is an annoying limitation.

Alex

**Comment by dbochicchio** [comment]
Thanks for the explanation, I found it by looking at the code. So, if I have the automation GUID, is it possible to call it directly?
Unfortunately I have no support for jq (it's a special linux distro on a funky hardware platform) and I have to rely on no-jq policy. It may be OK to just point the users to the JSON and identify the ID by theirselves, in my opinion.

**Comment by adn77** [comment]
As far as I know, the automation needs to be parameterized - that's why you have to send the `sequenceJSON` (extracting of which is the hard part).

Have a look at the OpenWRT project, they run on a bunch of hardware and have a buildroot environment that let's you easily crosscompile (https://openwrt.org/packages/pkgdata/jq)

If you only want to run the same routine, you'll need the AutomationID and the sequenceJSON and put it in a variable like this:
{"behaviorId":"'${AUTOMATION}'","sequenceJson":"'${SEQUENCE}'","status":"ENABLED"}

This can then be posted to:
"https://${ALEXA}/api/behaviors/preview"

The sequenceJSON needs to have lots of `"` escaped. You need to experiment which of these variables you're going to replace as well:
ALEXA_CURRENT_DEVICE_TYPE
ALEXA_CURRENT_DSN
ALEXA_CUSTOMER_ID
